version: 0.2

phases:
  pre_build:
   commands:
     - echo Logging in to Amazon ECR...
     - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
   commands:
     - echo Build started on 'date'
     - echo Building the Docker image...
     - docker build -t web:1 .
     - docker tag web:1 390138542770.dkr.ecr.us-east-1.amazonaws.com/jahangeer:latest
  post_build:
   commands:
     - echo Build completed on 'date'
     - ech0 Pushing the Docker image...
     - echo push 390138542770.dkr.ecr.us-east-1.amazonaws.com/jahangeer:latest
